# Quick Warm-up for Tensor

This session will give you a quick warm-up about tensor. The contents here are re-designed from TensorLy: 
- Tensor Basics: Click [here](http://tensorly.org/stable/user_guide/tensor_basics.html) for more details.
- Tensor Decomposition: Click [here](http://tensorly.org/stable/user_guide/tensor_decomposition.html) for more details.


## 1. Creating a tensor
A tensor is nothing more than a multi-dimensional array.
Let’s take for this example the tensor $\mathcal{X}$ defined by its frontal slices:

In [1]:
# import important packages
import numpy as np
import tensorly as tl
X = tl.tensor(np.arange(24).reshape((3, 4, 2)))

In [5]:
# look at the first slice of the tensor
X[..., 0]

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [4]:
# look at the second slice of the tensor
X[..., 1]

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

## 2. Unfolding

In [6]:
from tensorly import unfold

In [7]:
unfold(X, 0) # mode-1 unfolding

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [8]:
unfold(X, 1) # mode-2 unfolding

array([[ 0,  1,  8,  9, 16, 17],
       [ 2,  3, 10, 11, 18, 19],
       [ 4,  5, 12, 13, 20, 21],
       [ 6,  7, 14, 15, 22, 23]])

In [9]:
unfold(X, 2) # mode-3 unfolding

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23]])

## 3. Tensor Decomposition

### 3.1 CP Decomposition

Let's start with an easy 2-mode tensor, which is basically a matrix:

In [19]:
tensor = tl.tensor([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                        [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                        [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                        [ 0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
                        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])
tensor.shape

(12, 12)

**Notes**: Below the rank is selected as 2. But always remember, one of the biggest challenge for tensor decomposition is to determine the tensor rank

In [22]:
from tensorly.decomposition import parafac
factors = parafac(tensor, rank=2) 
len(factors)

2

The CP factor in Tensorly is in the format of list, with the following structure (updated at 22 Dec 2022):
- `factor[0]`: array of the weights $\lambda$
- `factor[1]`: list of the mode matrices $\mathbf{U}_1, \dots, \mathbf{U}_K$

In [36]:
factors

(weights, factors) : rank-2 CPTensor of shape (12, 12) 

In [37]:
[f.shape for f in factors[1]]

[(12, 2), (12, 2)]

From this cp tensor (presented as a list of matrices) you can reconstruct a full tensor:

In [25]:
print(tl.cp_to_tensor(factors))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### 3.2 Tucker Decomposition

In [38]:
from tensorly.decomposition import tucker
core, factors = tucker(tensor, rank=[2, 3])

In [39]:
core.shape

(2, 3)

In [40]:
factors

[array([[-0.00000000e+00,  4.16333634e-17],
        [-2.27675853e-01, -3.38866305e-01],
        [-2.27675853e-01, -3.38866305e-01],
        [-2.27675853e-01, -3.38866305e-01],
        [-4.15024769e-01,  2.78844833e-01],
        [-4.15024769e-01,  2.78844833e-01],
        [-4.15024769e-01,  2.78844833e-01],
        [-4.15024769e-01,  2.78844833e-01],
        [-2.27675853e-01, -3.38866305e-01],
        [-2.27675853e-01, -3.38866305e-01],
        [-2.27675853e-01, -3.38866305e-01],
        [ 0.00000000e+00,  0.00000000e+00]]),
 array([[ 0.00000000e+00, -5.55111512e-17,  1.70051223e-01],
        [ 2.27675853e-01, -3.38866305e-01, -3.77582862e-01],
        [ 2.27675853e-01, -3.38866305e-01,  8.75516572e-01],
        [ 2.27675853e-01, -3.38866305e-01, -1.24483428e-01],
        [ 4.15024769e-01,  2.78844833e-01,  0.00000000e+00],
        [ 4.15024769e-01,  2.78844833e-01,  0.00000000e+00],
        [ 4.15024769e-01,  2.78844833e-01,  0.00000000e+00],
        [ 4.15024769e-01,  2.78844833e-01, 

In [41]:
[f.shape for f in factors]

[(12, 2), (12, 3)]

As before, we can reconstruct a full tensor from our Tucker decomposition:

**Notes**: in the new `tucker_to_tensor` function, core and factors have to be input as a whole \[core, factors\].

In [45]:
from tensorly import tucker_to_tensor
tucker_to_tensor([core, factors])

array([[ 8.00005225e-33,  4.64369931e-17,  4.64369931e-17,
         4.64369931e-17, -3.82118711e-17, -3.82118711e-17,
        -3.82118711e-17, -3.82118711e-17,  4.64369931e-17,
         4.64369931e-17,  4.64369931e-17,  0.00000000e+00],
       [-6.29655996e-17,  2.33055848e-18, -5.40395971e-18,
         7.68350307e-19,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  7.68350307e-19,
         7.68350307e-19,  7.68350307e-19,  0.00000000e+00],
       [-6.29655996e-17,  2.33055848e-18, -5.40395971e-18,
         7.68350307e-19,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  7.68350307e-19,
         7.68350307e-19,  7.68350307e-19,  0.00000000e+00],
       [-6.29655996e-17,  2.33055848e-18, -5.40395971e-18,
         7.68350307e-19,  1.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  7.68350307e-19,
         7.68350307e-19,  7.68350307e-19,  0.00000000e+00],
       [ 5.74991096e-17,  1.00000000e+00,  1.0000000